POST http://localhost:3000/api/users 
Content-Type: application/json

{
    "username": "admin",
    "password": "qweradmin"
}

###
POST http://localhost:3000/api/auth 
Content-Type: application/json

{
    "username": "admin",
    "password": "qweradmin"
}
###
POST http://localhost:3000/api/comics 
Content-Type: application/json

{
    "name": "admin",
    "description": "qweradmin",
    "genreId": 1
}