POST http://localhost:3000/api/users 
Content-Type: application/json

{
    "username": "admin",
    "password": "qweradmin"
}
###
POST http://localhost:3000/api/genres
Content-Type: application/json

{
    "name": "Gunung Meletus"
}
###
DELETE http://localhost:3000/api/episodes/f5cd7d5c-0257-42e5-9246-225610ce77c8
Content-Type: application/json
###
POST http://localhost:3000/api/auth 
Content-Type: application/json

{
    "username": "admin",
    "password": "qweradmin"
}
###
POST http://localhost:3000/api/panels 
Content-Type: application/json

{
    "episodeId": "968164ea-ff04-40ee-a38a-c1681c345c13",
    "image": {
    "type": "Buffer",
    "data": [
        117,
        171,
        90,
        138,
        102,
        160,
        123,
        250,
        103,
        129,
        182,
        172,
        123,
        174,
        34,
        84,
        19,
        145,
        195,
        66,
        134
    ]
}
}
###
POST http://localhost:3000/api/comics 
Content-Type: application/json

{
    "name": "admin",
    "description": "qweradmin",
    "genreId": "1"
}

###
POST http://localhost:3000/api/comics/fc6f1f7c-0b3a-44c7-8119-4320794968b3
Content-Type: application/json

{
    "comicId": "2f9cb0f0-8c14-4edb-8589-356642ac06c9"
}