import Head from "next/head";
import Image from "next/image";
import React, { ReactNode } from "react";

interface Props {
  children: ReactNode;
}
const MainLayout: React.FC<Props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Komiga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#F6F6F6]">{children}</main>

      <footer className="bg-zinc-800 text-white text-center py-10">
        &copy; KOMIGA 2022
      </footer>
    </div>
  );
};

export default MainLayout;
