import Head from "next/head";
import Image from "next/image";
import React, { ReactNode } from "react";

interface Props {
  children: ReactNode;
}
const MainLayout: React.FC<Props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Komiga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#F6F6F6]">{children}</main>

      <footer>
        Powered by{" "}
        <span>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
};

export default MainLayout;
